import os
CC = os.getenv('CC')
print(CC)

DEBUG_FLAGS = os.getenv('DEBUG_FLAGS')
print(DEBUG_FLAGS)

AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
Print("access key")
print(AWS_SECRET_ACCESS_KEY)
print(AWS_ACCESS_KEY_ID)

BITBUCKET_COMMON_CREDS_USR = os.getenv('BITBUCKET_COMMON_CREDS_USR')
print(BITBUCKET_COMMON_CREDS_USR)
BITBUCKET_COMMON_CREDS_PSW = os.getenv('BITBUCKET_COMMON_CREDS_PSW')
print("password")
print(BITBUCKET_COMMON_CREDS_PSW)
